version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: local_pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - //wsl.localhost/Ubuntu/root/docker/persistent:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: nanasuryana335@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

networks:
  default:
    name: postgres-network